// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PracNet7ApiProB01.Model.Entities;

#nullable disable

namespace PracNet7ApiProB01.Model.Migrations
{
    [DbContext(typeof(PracNet7ApiDbContext))]
    [Migration("20240706095740_UpdateEnDb01")]
    partial class UpdateEnDb01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("CustomerPoint")
                        .HasColumnType("real");

                    b.Property<Guid>("GenUserInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastPurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GenUserInfoId")
                        .IsUnique();

                    b.ToTable("customes_tbl");
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.GeneralRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GenRoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenRoleTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("general_roles_tbl");
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.GeneralUserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GenRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenRoleId");

                    b.ToTable("general_user_info_tbl");
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenUserInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("StaffRoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("StaffRoleTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenUserInfoId")
                        .IsUnique();

                    b.HasIndex("StaffRoleId");

                    b.ToTable("staffs_tbl");
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.StaffRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("StaffRoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffRoleTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("staff_roles_tbl");
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.Customer", b =>
                {
                    b.HasOne("PracNet7ApiProB01.Model.Entities.GeneralUserInfo", "GeneralUserInfo")
                        .WithOne("Customer")
                        .HasForeignKey("PracNet7ApiProB01.Model.Entities.Customer", "GenUserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralUserInfo");
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.GeneralUserInfo", b =>
                {
                    b.HasOne("PracNet7ApiProB01.Model.Entities.GeneralRole", "GeneralRole")
                        .WithMany("GeneralUserInfos")
                        .HasForeignKey("GenRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralRole");
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.Staff", b =>
                {
                    b.HasOne("PracNet7ApiProB01.Model.Entities.GeneralUserInfo", "GeneralUserInfo")
                        .WithOne("Staff")
                        .HasForeignKey("PracNet7ApiProB01.Model.Entities.Staff", "GenUserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracNet7ApiProB01.Model.Entities.StaffRole", "StaffRole")
                        .WithMany("Staffs")
                        .HasForeignKey("StaffRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralUserInfo");

                    b.Navigation("StaffRole");
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.GeneralRole", b =>
                {
                    b.Navigation("GeneralUserInfos");
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.GeneralUserInfo", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Staff")
                        .IsRequired();
                });

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.StaffRole", b =>
                {
                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
