// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PracNet7ApiProB01.Model.Entities;

#nullable disable

namespace PracNet7ApiProB01.Model.Migrations
{
    [DbContext(typeof(PracNet7ApiDbContext))]
    partial class PracNet7ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PracNet7ApiProB01.Model.Entities.GeneralRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GenRoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenRoleTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("general_roles_tbl");
                });
#pragma warning restore 612, 618
        }
    }
}
