<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PracNet7ApiProB01.Dto\PracNet7ApiProB01.Dto.csproj" />
    <ProjectReference Include="..\PracNet7ApiProB01.Model\PracNet7ApiProB01.Model.csproj" />
    <ProjectReference Include="..\PracNet7ApiProB01.Utils\PracNet7ApiProB01.Utils.csproj" />
  </ItemGroup>

</Project>
