// <auto-generated />
using System;
using BlogWebApi.Model.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogWebApi.Model.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241127021651_DbUpdate-Config-dtype-blogs_tbl-b01")]
    partial class DbUpdateConfigdtypeblogs_tblb01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogWebApi.Model.Entities.BlogCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlogCategoryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfModified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("blog_cates_tbl");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.BlogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("blogs_tbl");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("comments_tbl");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.InteractionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InteractionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("InteractionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("interaction_tbl");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.InteractionTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("interaction_types_tbl");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.LikeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("likes_tbl");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("roles_tbl");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a633bf0-09ba-4ad2-9c0e-2fb61fba200a"),
                            DateOfCreated = new DateTime(2024, 11, 27, 9, 16, 50, 723, DateTimeKind.Local).AddTicks(1534),
                            DateOfModified = new DateTime(2024, 11, 27, 9, 16, 50, 724, DateTimeKind.Local).AddTicks(981),
                            RoleTitle = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("ef367267-a0cc-4608-b549-358e10a6c405"),
                            DateOfCreated = new DateTime(2024, 11, 27, 9, 16, 50, 724, DateTimeKind.Local).AddTicks(1181),
                            DateOfModified = new DateTime(2024, 11, 27, 9, 16, 50, 724, DateTimeKind.Local).AddTicks(1182),
                            RoleTitle = "USER"
                        });
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.ShareEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("shares_tbl");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users_tbl");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.BlogEntity", b =>
                {
                    b.HasOne("BlogWebApi.Model.Entities.BlogCategoryEntity", "BlogCategory")
                        .WithMany("BlogEntities")
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogWebApi.Model.Entities.UserEntity", "UserEntity")
                        .WithMany("BlogEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlogCategory");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.CommentEntity", b =>
                {
                    b.HasOne("BlogWebApi.Model.Entities.BlogEntity", "BlogEntity")
                        .WithMany("CommentEntities")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogWebApi.Model.Entities.UserEntity", "UserEntity")
                        .WithMany("CommentEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlogEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.InteractionEntity", b =>
                {
                    b.HasOne("BlogWebApi.Model.Entities.BlogEntity", "BlogEntity")
                        .WithMany("InteractionEntities")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogWebApi.Model.Entities.InteractionTypeEntity", "InteractionTypeEntity")
                        .WithMany("InteractionEntities")
                        .HasForeignKey("InteractionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogWebApi.Model.Entities.UserEntity", "UserEntity")
                        .WithMany("InteractionEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlogEntity");

                    b.Navigation("InteractionTypeEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.LikeEntity", b =>
                {
                    b.HasOne("BlogWebApi.Model.Entities.BlogEntity", "BlogEntity")
                        .WithMany("LikeEntities")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogWebApi.Model.Entities.UserEntity", "UserEntity")
                        .WithMany("LikeEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlogEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.ShareEntity", b =>
                {
                    b.HasOne("BlogWebApi.Model.Entities.BlogEntity", "BlogEntity")
                        .WithMany("ShareEntities")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogWebApi.Model.Entities.UserEntity", "UserEntity")
                        .WithMany("ShareEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlogEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.UserEntity", b =>
                {
                    b.HasOne("BlogWebApi.Model.Entities.RoleEntity", "RoleEntity")
                        .WithMany("UserEntities")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleEntity");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.BlogCategoryEntity", b =>
                {
                    b.Navigation("BlogEntities");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.BlogEntity", b =>
                {
                    b.Navigation("CommentEntities");

                    b.Navigation("InteractionEntities");

                    b.Navigation("LikeEntities");

                    b.Navigation("ShareEntities");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.InteractionTypeEntity", b =>
                {
                    b.Navigation("InteractionEntities");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserEntities");
                });

            modelBuilder.Entity("BlogWebApi.Model.Entities.UserEntity", b =>
                {
                    b.Navigation("BlogEntities");

                    b.Navigation("CommentEntities");

                    b.Navigation("InteractionEntities");

                    b.Navigation("LikeEntities");

                    b.Navigation("ShareEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
